<?php

namespace App\model\users;
use App\model\BloodBankBranch\BloodBank;
use App\model\database\dbModel;

class organization extends Person
{

    protected string $Organization_ID='';
    protected string $Organization_Name='';
    protected string $Email='';
    protected string $Contact_No='';
    protected string $City='';
    protected string $Created_At='';
    protected string $Password='';
    protected string $Profile_Image='';
    protected string $Updated_At = '';

    public function getName():string
    {
        return $this->Organization_Name;
    }
    public function getID()
    {
        return $this->Organization_ID;
    }

    public function setID(string $Id)
    {
        $this->UID=$Id;
    }

    public function getRole(): string
    {
        return 'Organization';
    }

    /**
     * @return string
     */
//    public function getPosition(): string
//    {
//        return $this->Position;
//    }

    /**
     * @param string $Position
     */
//    public function setPosition(string $Position): void
//    {
//        $this->Position = $Position;
//    }

    /**
     * @param string $Branch_ID
     */
//    public function setBranchID(string $Branch_ID): void
//    {
//        $this->Branch_ID = $Branch_ID;
//    }

    /**
     * @param string $Joined_Date
     */
    public function setJoinedDate(string $Joined_Date): void
    {
        $this->Created_At = $Joined_Date;
    }



    public function rules(): array
    {
        return [
            'Organization_ID'=>[self::RULE_REQUIRED,self::RULE_UNIQUE],
            'Organization_Name'=>[self::RULE_REQUIRED],
            'Organization_Email'=>[self::RULE_REQUIRED,self::RULE_UNIQUE,self::RULE_EMAIL],
            'Address1'=>[self::RULE_REQUIRED],
            'Address2'=>[self::RULE_REQUIRED],
            'City'=>[self::RULE_REQUIRED],
           'Contact_No'=>[self::RULE_REQUIRED,self::RULE_MOBILE_NO],
        ];
    }

    public static function getTableShort(): string
    {
        return 'mo';
    }

    public static function tableName(): string
    {
        return 'Organizations';
    }

    public static function PrimaryKey(): string
    {
        return 'Organization_ID';
    }

    public function attributes(): array
    {
        return [
            'Organization_ID',
            'Organization_Name',
            'Created_At',
            'Updated_At',
            'Status',
            'Email',
            'Address1',
            'Address2',
            'City',
            'Profile_Image',
            'Contact_No',
        ];
    }

    public function GetAttributesValue($attributes)
    {
        return $this->{$attributes};
    }

    public function labels(): array
    {
        return [
            'Organization_ID'=>'UID',
            'Organization_Name'=>'Organization_Name',
            'Joined_Date'=>'Joined Date',
            'Status'=>'Status',
            'Organization_Email'=>'Email',
            'Address1'=>'Address1',
            'Address2'=>'Address2',
            'City'=>'City',
            'ImageURL'=>'Image URL',
            'Contact_No'=>'Contact No',

        ];
    }
    public function getProfileImage(): string
    {
        return $this->Profile_Image; // TODO: Change the autogenerated stub
    }
    public function setProfileImage(string $Profile_Image): void
    {
         $this->Profile_Image = $Profile_Image; // TODO: Change the autogenerated stub
    }
}